/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visualizacion;
import Controlador.*;
import javax.swing.table.DefaultTableModel;//Ocupas Importar esta libreria

/**
 *
 * @author ALLCH
 */
public class VisualizarProductos extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarProductos
     */
    Controlador objControlador;
    public VisualizarProductos(Controlador objControlador) {
        initComponents();
        this.objControlador = objControlador;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMostrarProductos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoPrueba = new javax.swing.JTextArea();
        btPrincipalProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMostrarProductos.setText("Mostrar Productos");
        btnMostrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarProductosActionPerformed(evt);
            }
        });

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel2.setText("Visualizar Productos");

        textoPrueba.setColumns(20);
        textoPrueba.setRows(5);
        jScrollPane2.setViewportView(textoPrueba);

        btPrincipalProductos.setText("Principal");
        btPrincipalProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrincipalProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(btnMostrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btPrincipalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(btPrincipalProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(btnMostrarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarProductosActionPerformed
      
      String consulta = "SELECT * FROM producto";
      objControlador.llenarTablaProductos(tablaProductos,consulta);
    }//GEN-LAST:event_btnMostrarProductosActionPerformed

    private void tablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMouseClicked
        int row = tablaProductos.rowAtPoint(evt.getPoint());

   /* row devolvera -1 si se ha clicado fuera de la fila pero dentro de la tabla, si no devolvera el indice de la fila en la que se ha clicado. */

       
        textoPrueba.append((String) tablaProductos.getValueAt(row, 0));
        textoPrueba.setText((String) tablaProductos.getValueAt(row, 1));

    }//GEN-LAST:event_tablaProductosMouseClicked

    private void btPrincipalProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrincipalProductosActionPerformed
        DashBoard volverHome= new DashBoard(objControlador);
        volverHome.setVisible(true);
        this.dispose(); // instruccion que cierra la ventana actual
    }//GEN-LAST:event_btPrincipalProductosActionPerformed

//   public void mostrarProductos() {
//
//        // String[][] arregloEntrada = new String[2][7];
//       String[][] arregloEntrada ;
//       arregloEntrada  = (objInterface.mostrarProductos());     /////?????????????????????????? no se creo el new que pasa???   
//       int numCol = 7;
//       int numFilas = 2;
//        
//        DefaultTableModel  model = (DefaultTableModel )tablaProductos.getModel();
//        model.setRowCount(11);   //Cantidad de filas
//        //model.setColumnCount(4);  //cantidad de columnas
//        
//        //Se agregan los datos del cliente para que aparezcan en el encabezado de la tabla 
//        model.addColumn("Producto");
//        model.addColumn("Codigo");
//        model.addColumn("Cantidad");
//        model.addColumn("Valor Compra");
//        model.addColumn("Valor Venta");
//        model.addColumn("Proveedor");
//        model.addColumn("Descripcion");
//        
//        for(int i = 0; i<  numFilas; i++){
//            
//            for (int j =0; j < numCol; j++) {
//            
//            tablaProductos.setValueAt(arregloEntrada[j][i],i,j); // dato, posicion en x, posicion en y
//            
//            }
//           
//        }
//   }  
   
//   public void mostrarProductosVentas() {
//
//        // String[][] arregloEntrada = new String[2][7];
//       String[][] arregloEntrada ;
//       arregloEntrada  = (objInterface.mostrarProductos());     /////?????????????????????????? no se creo el new que pasa???   
//       int numCol = 7;
//       int numFilas = 2;
//        
//        DefaultTableModel  model = (DefaultTableModel )tablaProductos.getModel();
//        model.setRowCount(11);   //Cantidad de filas
//        //model.setColumnCount(4);  //cantidad de columnas
//        
//        //Se agregan los datos del cliente para que aparezcan en el encabezado de la tabla 
//        model.addColumn("Producto");
//        model.addColumn("Codigo");
//        model.addColumn("Cantidad");
//        model.addColumn("Valor Compra");
//        model.addColumn("Valor Venta");
//        model.addColumn("Proveedor");
//        model.addColumn("Descripcion");
//        
//        for(int i = 0; i<  numFilas; i++){
//            
//            for (int j =0; j < numCol; j++) {
//            
//            tablaProductos.setValueAt(arregloEntrada[j][i],i,j); // dato, posicion en x, posicion en y
//            
//            }
//           
//        }
//   }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPrincipalProductos;
    public javax.swing.JButton btnMostrarProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tablaProductos;
    private javax.swing.JTextArea textoPrueba;
    // End of variables declaration//GEN-END:variables
}
